name: Deploy Terraform Storage Account

on:
  workflow_dispatch: # Trigger manually via GitHub Actions interface

jobs:
  deploy-storage-account:
    runs-on: ubuntu-latest
    environment:
      name: dev

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed

    steps:
    # Step 1: Login to Azure using OIDC
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 2: Deploy the storage account using Azure CLI
    - name: Deploy Storage Account
      uses: azure/cli@v1
      with:
        inlineScript: |
          RESOURCE_GROUP="rg-integrationmanagement-aue"
          STORAGE_ACCOUNT_NAME="saterraformstateauedev" # Ensures globally unique name
          LOCATION="australiaeast"
          SKU="Standard_LRS"

          # Create the resource group if it doesn't exist
          az group create --name $RESOURCE_GROUP --location $LOCATION

          # Create the storage account
          az storage account create \
            --name $STORAGE_ACCOUNT_NAME \
            --resource-group $RESOURCE_GROUP \
            --location $LOCATION \
            --sku $SKU \
            --kind StorageV2
