name: "Self Hosted Network Test"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        type: string

jobs:
  deployment:
    name: "Deploy to ${{ inputs.environment }}"
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      # Log in to Azure with OIDC
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Test KeyVault access
        run: |
          az keyvault secret list --vault-name kv-tewheke-dev-aue