name: Setup GitHub Runner

on:
  workflow_dispatch: # Trigger manually via GitHub Actions interface

jobs:
  setup-gitHub-runner:
    runs-on: ubuntu-latest
    environment:
      name: dev

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed

    steps:
    # Step 1: Login to Azure using OIDC
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 2: Build the GitHub image into ACR
    - name: Build GitHub Runner Docker Image
      uses: azure/cli@v1
      with:
        inlineScript: |
          CONTAINER_IMAGE_NAME="actions-runner:2.321.0"
          CONTAINER_REGISTRY_NAME="acrtewhekedevaue"

          # Create the image in the ACR
          az acr build \
            --registry "$CONTAINER_REGISTRY_NAME" \
            --image "$CONTAINER_IMAGE_NAME" \
            --file images/Dockerfile \
            "https://github.com/actions/runner.git"
            