name: Setup 2 Self-Hosted GitHub Runner Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The target environment for deployment that is lowest of the group (e.g., dev, stg, prd)"
        required: true
        type: string
      environment_group:
        description: "The target environment group for deployment (e.g., npe, ppe, prd)"
        required: true
        type: string
      root_directory:
        description: "Root directory where Terraform config is located"
        required: false
        default: "GitHubRunner/Infrastructure"
        type: string
      sub_directory:
        description: "Sub-directory containing resource Terraform files"
        required: false
        default: "GitHubRunner/Infrastructure"
        type: string
      runner:
        description: "Type of runner to use for deployment. Defaults to GitHub hosted Linux"
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  deploy-runner-infrastructure:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # To access repository files if needed
    uses: MitchAbelDevOps/DevOps/.github/workflows/deploy-resource.yaml@main
    with:
      environment: "${{ inputs.environment }}"
      root_directory: ${{ inputs.root_directory }}
      sub_directory: ${{ inputs.sub_directory }}
      terraform_state_filename: runnerinfra-mitchtest.${{ inputs.environment_group }}.tfstate
      runner: ${{  inputs.runner }}
    secrets: inherit
