name: Setup 2 Self-Hosted GitHub Runner Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: "The target environment for deployment (e.g., dev, test, prod)"
        required: true
        type: string
      root_directory:
        description: "Root directory where Terraform config is located"
        required: false
        default: "GitHubRunner/Infrastructure"
        type: string
      sub_directory:
        description: "Sub-directory containing resource Terraform files"
        required: false
        default: "GitHubRunner/Infrastructure"
        type: string
      terraform_state_filename:
        description: "Name for the tfstate blob to create for this resource"
        required: false
        default: "cae-tewheke.tfstate"
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "The target environment for deployment (e.g., dev, test, prod)"
        required: true
        type: string
      root_directory:
        description: "Root directory where Terraform config is located"
        required: false
        default: "GitHubRunner/Infrastructure"
        type: string
      sub_directory:
        description: "Sub-directory containing resource Terraform files"
        required: false
        default: "GitHubRunner/Infrastructure"
        type: string
      terraform_state_filename:
        description: "Name for the tfstate blob to create for this resource"
        required: false
        default: "cae-tewheke.tfstate"
        type: string

jobs:
  deploy-runner-infrastructure:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # To access repository files if needed
    uses: MitchAbelDevOps/DevOps/.github/workflows/deploy-resource.yaml@main
    with:
      environment: "${{ inputs.environment }}"
      root_directory: ${{ inputs.root_directory }}
      sub_directory: ${{ inputs.sub_directory }}
      terraform_state_filename: ${{  inputs.terraform_state_filename }}
    secrets: inherit
