name: Setup GitHub Runner

on:
  workflow_dispatch: # Trigger manually via GitHub Actions interface

jobs:
  setup-gitHub-runner:
    runs-on: ubuntu-latest
    environment:
      name: dev

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed

    steps:
    # Step 1: Login to Azure using OIDC
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name acrtewhekedevaue

    - name: Pull Docker image from GitHub Container Registry
      run: |
        docker pull ghcr.io/actions/actions-runner:2.321.0

    - name: Tag the Docker image for ACR
      run: |
        docker tag ghcr.io/actions/actions-runner:2.321.0 acrtewhekedevaue.azurecr.io/actions-runner:2.321.0

    - name: Push Docker image to ACR
      run: |
        docker push acrtewhekedevaue.azurecr.io/actions-runner:2.321.0
