name: 'Terraform Plan'

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory containing Terraform files'
        required: true
        type: string
      var_file:
        description: 'Variable file for Terraform plan'
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform Plan
      run: |
        terraform plan \
          -input=false \
          -var-file="${{ inputs.var_file }}" \
          -out=deployment.tfplan
      working-directory: ${{ inputs.working_directory }}
