name: Terraform Init

on:
  workflow_call:
    inputs:
      storage_account_name:
        required: true
        type: string
      container_name:
        required: true
        type: string
      state_filename:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      storage_account_key:
        description: 'Terraform Storage Account Key'
        required: true
        type: string

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Install Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'

    # Terraform Init
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ inputs.storage_account_name }}" \
          -backend-config="container_name=${{ inputs.container_name }}" \
          -backend-config="key=${{ inputs.state_filename }}" \
          -backend-config="access_key=${{ inputs.storage_account_key }}"
      working-directory: ${{ inputs.working_directory }}

    # Terraform Format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{ inputs.working_directory }}
